# Mokymo triukai

## Iliustratoriai

https://lizawolfson.co.uk/


## Kahoot

Kahoot yra testų platforma, kuri palengvina žinių testavimą. Sukurti klausimai gali būti rodomi ekrane, o moksleiviai, naudodamiesi telefonais, gali atsakyti į klausimus.

Viešai prieinamų Kahoot sąrašas:

* [Sukurti viešai prieinamus Kahoot](https://kahoot.com/academy/)

## Simuliacijos

* [Fitting Multivariate ODE with brms](https://magesblog.com/post/2021-02-08-fitting-multivariate-ode-models-with-brms/)

## Zinai

Nuorodos:

* [Kaip pasigaminti ziną](http://experimentwithnature.com/03-found/experiment-with-paper-how-to-make-a-one-page-zine/)

## Straipsnių aptarimas

Moksleiviai po biologijos kurso turi gebėti suprasti biologiją. Vienas geriausių būdų tai patikrinti - paprašyti, jog moksleivis pristatytų ir papasakotų apie straipsnį savo žodžiais. Mokslinių straipsnių turinys yra tankus, todėl moksleivis turi gerai įsigilinti ir atnešti "esmę". Tai neišvengiamai turi būti daroma savais žodžiais, nes mokslinio straipsnio žargonas yra per tankus ir sunkiai atpasakojamas.

Rekomenduojami straipsniai aptarimui

Žmogaus biologija:  

* [The distribution of cellular turnover in the human body](https://www.nature.com/articles/s41591-020-01182-9)
* [Evidence for cardiomyocyte renewal in humans](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2991140/)

Molekulinė biologija:

* [The lifecycle of the neuronal microtubule transport machinery](https://www.sciencedirect.com/science/article/abs/pii/S1084952119301569)
* [Immunogenicity and structures of a rationally designed prefusion MERS-CoV spike antigen](https://www.pnas.org/content/114/35/E7348?__cf_chl_jschl_tk__=9893779ff7e5238434b47a68064e21abd7e897d3-1613604269-0-ARYvwnUKZQX2McsE23m3cyIt6GlEYx-BqjwNnyETS0gCr0lSjouy2gvAp9dH86UCcy8bCM_MvWjzCo6FAR3XQZF_HEBpYGQgFiwfXNQjOMk-mZ5smzZxZiYDMYMs0TY3Frymu-NJCxaCiDKQEaFupJVgEREMWwvuGHskfNae0WTVqAIOynOs9Os7dLDovTMiBCTqkoHBZ1Ctv2AKw6rv87Uv2HhD4X6Rtkc3udcS1RKslcGj1UDb_hh9o_meOMbmRsmA6_4-F4nSNWN9fK3KtizBOnHVWDlgR-ueMcnJipAKGEgPlyfBsgVeyRawg26rZxcPL-59WyzcOvArnl2Kj0U), daugiau apie straipsnį [čia](https://twitter.com/EricTopol/status/1338210550740762624).

Mikroskopija

* [Evaluation and development of deep neural networks for image super-resolution in optical microscopy](https://www.nature.com/articles/s41592-020-01048-5)

Straipsnius rekomenduojame gauti per Sci-Hub platformą.

## Paaiškinti memą

Internete yra didelis pasirinkimas memų, susijusių su biologija. Kai kurie iš jų nėra informatyvūs, tačiau kai kurie yra paremti biologijos principais, kuriuos moksleiviai turi išmanyti. Užsiėmimo tikslas yra moksleiviams atpažinti biologinius memus, suprasti jų esmę ir paaiškinti, kodėl jie buvo taip sukurti.

Prieš užsiėmimą moksleiviai turėtų internete rasti memų ar iliustracijų, susijusių su biologija. Taip pat užduočiai yra tinkami komiksai ar kitokio tipo iliustracijos, jeigu galima jas paaiškinti. Moksleiviai turėtų ieškoti memų patys, tačiau esant reikalui mokytojas turėtų turėti rezervą memų, kuriuos moksleiviai turėtų paaiškinti.

Memų ir iliustracijų šaltiniai, kuriais galima naudotis:  

* [xkcd komiksas apie mRNR vakciną](https://xkcd.com/2425/)
* [xkcd komiksas apie statistinį reikšmingumą](https://xkcd.com/882/)
* [High Recombination Frequency Biology Memes](https://www.facebook.com/HFRBiologyMemes)
* [Photosynthetic Memes for Botanical Teens](https://www.facebook.com/botanicalmemes)

Twitter:

* [GAGA ir GUGU](https://twitter.com/kirvers/status/1359007532384067586)

## Kiti galimi įrankiai

* [Objection.lol](objection.lol) - Ace Atorney Objection generatorius
